[workspace]
members = [
    "access-control",
    "authorization",
    "batch-ops",
    "constant-product-amm",
    "contract-factory",
    "counter",
    "emergency-stop",
    "error-handling",
    "escrow-multiparty",
    "hello-world",
    "htlc-swap",
    "oracle-consumer",
    "reentrancy-guard",
    "simple-dao",
    "simple-voting",
    "staking",
    "timelock-vault",
    "token-snapshot",
    "token-transfer",
    "token-vesting",
    "token-wrapper",
    "upgradeable",
    "multisig-wallet",
]
resolver = "2"
